# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{devnull}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["H.Hiro (Maraigue)"]
  s.date = %q{2011-03-28}
  s.description = %q{DevNull behaves a null file, and works like an IO object. For example:

dn = DevNull.new
dn.puts "foo" # => nil (do nothing)
dn.gets # => nil
dn.read # => ""

The library may be a good solution if you would like to switch whether an input/output file is needed. For example:

def some_process(arg, logfile = nil)
  # You may set an IO object as 'logfile', and logs are written to the file.
  
  result = process1(arg)
  logfile.puts result if logfile
  
  result = process2(arg)
  logfile.puts result if logfile
  
  result = process3(arg)
  logfile.puts result if logfile
end

can be rewritten as follows:

def some_process(arg, logfile = DevNull.new)
  logfile.puts process1(arg)
  logfile.puts process2(arg)
  logfile.puts process3(arg)
end
}
  s.email = %q{main@hhiro.net}
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "devnull.gemspec",
    "lib/devnull.rb",
    "spec/devnull_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/maraigue/devnull}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.6.2}
  s.summary = %q{Ruby implementation of null file (like /dev/null on Un*x, NUL on Windows)}
  s.test_files = [
    "spec/devnull_spec.rb",
    "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 2.3.0"])
      s.add_development_dependency(%q<bundler>, [">= 1.0.0"])
      s.add_development_dependency(%q<jeweler>, [">= 1.5.2"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
    else
      s.add_dependency(%q<rspec>, [">= 2.3.0"])
      s.add_dependency(%q<bundler>, [">= 1.0.0"])
      s.add_dependency(%q<jeweler>, [">= 1.5.2"])
      s.add_dependency(%q<rcov>, [">= 0"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 2.3.0"])
    s.add_dependency(%q<bundler>, [">= 1.0.0"])
    s.add_dependency(%q<jeweler>, [">= 1.5.2"])
    s.add_dependency(%q<rcov>, [">= 0"])
  end
end

